### ISSUE TITLE
fqdn_attributes = json_response['results'][0]['attributes'][0] -> KeyError: 'attributes'

### ISSUE THREAD

**Issue by VladoPortos** [vmware-samples/sddc-import-export-for-vmware-cloud-on-aws#89]
### Describe the bug

Script fails during export on:

```
.
.
.
Beginning NSX Layer 7 FQDN profile export
Traceback (most recent call last):
  File "/home/vladoportos/sddc-import-export-for-vmware-cloud-on-aws/sddc_import_export.py", line 1006, in <module>
    main(sys.argv[1:])
  File "/home/vladoportos/sddc-import-export-for-vmware-cloud-on-aws/sddc_import_export.py", line 690, in main
    retval = ioObj.export_fqdn_attribute()
  File "/home/vladoportos/sddc-import-export-for-vmware-cloud-on-aws/VMCImportExport.py", line 1027, in export_fqdn_attribute
    fqdn_attributes = json_response['results'][0]['attributes'][0]
KeyError: 'attributes'
```

### Reproduction steps

1. normal setup for export, with default settings.
2. no vcenter.ini setup 
3. no aws.ini setup 
...

### Expected behavior

Finish the export

**Comment by VladoPortos** [comment]
I have printed out the variable:

```
    def export_fqdn_attribute(self):
        """"Export FQDN custom attributes for L7 context profiles"""
        url = f'{self.proxy_url}/policy/api/v1/infra/context-profiles/custom-attributes/default'
        response = self.invokeVMCGET(url)
        if response is None or response.status_code != 200:
            self.error_handling(response)
            return False
        else:
            json_response = response.json()
            print(json_response)
.
.
.
```

`{'results': [{'marked_for_delete': False, 'overridden': False, '_protection': 'NOT_PROTECTED'}], 'result_count': 1}`

Looks like there is situation when the `attributes `is not there.

I have changed the function a little to account for this:
IN: VMCImportExport.py
Code Line Start: 1018

```
    def export_fqdn_attribute(self):
        """"Export FQDN custom attributes for L7 context profiles"""
        url = f'{self.proxy_url}/policy/api/v1/infra/context-profiles/custom-attributes/default'
        response = self.invokeVMCGET(url)
        if response is None or response.status_code != 200:
            self.error_handling(response)
            return False
        else:
            json_response = response.json()
            # Check if 'attributes' key exists in the first item of 'results'
            if 'attributes' in json_response.get('results', [{}])[0]:
                fqdn_attributes = json_response['results'][0]['attributes'][0]
                fname = self.export_path / self.nsx_l7_fqdn_filename
                with open(fname, 'w') as outfile:
                    json.dump(fqdn_attributes, outfile, indent=4)
                return True
            else:
                # Handle the case where 'attributes' key is not found
                print("No 'attributes' key found in the response.")
                # Add any specific handling you need here
                return False
```
